# Generated by Django 5.0.4 on 2024-05-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
    ]
