# Generated by Django 5.0.4 on 2024-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slots',
            field=models.IntegerField(null=True),
        ),
    ]
