# Generated by Django 5.0.4 on 2024-05-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commission_people_required_commission_status_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_commissions', to='user_management.profile'),
        ),
    ]
