# Generated by Django 5.0.2 on 2024-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
