# Generated by Django 5.0.2 on 2024-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='entry',
            field=models.TextField(null=True),
        ),
    ]
